-- =====================================================================
-- Migration: Organization Accounts & Registration
-- Description:
--   - Links organizations to their Supabase Auth login account via user_id
--   - Case-insensitive unique name index
--   - public.is_organization_name_available(text) check function
--   - Trigger on auth.users to auto-create organization row on signup
-- =====================================================================

-- rollback:
-- drop trigger if exists on_auth_organization_created on auth.users;
-- drop function if exists public.handle_new_organization_user();
-- drop function if exists public.is_organization_name_available(text);
-- drop index if exists organizations_name_lower_uidx;
-- alter table public.organizations drop constraint if exists organizations_user_id_key;
-- alter table public.organizations drop constraint if exists organizations_user_id_fkey;
-- alter table public.organizations drop column if exists user_id;

-- 1. Link organizations to their login account
alter table public.organizations add column if not exists user_id uuid;

do $$ begin
  begin alter table public.organizations add constraint organizations_user_id_fkey
        foreign key (user_id) references auth.users(id) on delete set null; exception when duplicate_object then null; end;
  begin alter table public.organizations add constraint organizations_user_id_key unique (user_id); exception when duplicate_object then null; end;
end $$;

-- Case-insensitive unique name (skipped with a notice if duplicates already exist — fix them and re-run)
do $$ begin
  create unique index if not exists organizations_name_lower_uidx on public.organizations (lower(trim(name)));
exception when unique_violation then raise notice 'Duplicate organization names exist; case-insensitive unique index NOT created.';
end $$;

-- 2. Name availability check for the form (anon-callable, returns only a boolean)
create or replace function public.is_organization_name_available(p_name text)
returns boolean language sql stable security definer set search_path = public as $$
  select not exists (select 1 from public.organizations where lower(trim(name)) = lower(trim(p_name)));
$$;
grant execute on function public.is_organization_name_available(text) to anon, authenticated;

-- 3. Create the organizations row when an ORGANIZATION account signs up
create or replace function public.handle_new_organization_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_name    text := nullif(trim(coalesce(new.raw_user_meta_data->>'organization_name','')), '');
  v_members int  := 1;
begin
  if coalesce(new.raw_user_meta_data->>'account_type','') <> 'organization' then
    return new;                                   -- normal citizen signup: do nothing
  end if;
  if v_name is null then
    raise exception 'Organization name is required';
  end if;
  begin
    v_members := coalesce(nullif(new.raw_user_meta_data->>'member_count','')::int, 1);
  exception when others then v_members := 1;
  end;
  v_members := greatest(1, least(10000, v_members));

  insert into public.organizations (name, email, member_count, user_id)
  values (v_name, lower(new.email), v_members, new.id);   -- team_code is generated by the existing organizations trigger
  return new;
end $$;

drop trigger if exists on_auth_organization_created on auth.users;
create trigger on_auth_organization_created
  after insert on auth.users
  for each row execute function public.handle_new_organization_user();

-- 4. Realtime + API cache
do $$ begin
  begin alter publication supabase_realtime add table public.organizations; exception when duplicate_object then null; end;
end $$;
notify pgrst, 'reload schema';
